import { POLineItem, DocumentIssueRecord } from '../types';

export const INITIAL_PO_DATA: POLineItem[] = [
  // PO-2026-8801 - Acme Engineering Ltd (2 lines)
  {
    id: 'pol-sample-1',
    customerName: 'Acme Engineering Ltd',
    destination: 'Dar es Salaam Port - Site A',
    poNumber: 'PO-2026-8801',
    contract: 'CNT-EAST-091',
    itemDescription: 'High-Grade Steel Reinforcement Bars 16mm (Grade 500)',
    date: '2026-08-15',
    unitOfMeasure: 'TONS',
    quantity: 50,
    unitCost: 850.00,
    unitPrice: 980.00,
    valueBeforeVat: 49000.00,
    vatRate: 0.18,
    vatAmount: 8820.00,
    valueAfterVat: 57820.00,
  },
  {
    id: 'pol-sample-2',
    customerName: 'Acme Engineering Ltd',
    destination: 'Dar es Salaam Port - Site A',
    poNumber: 'PO-2026-8801',
    contract: 'CNT-EAST-091',
    itemDescription: 'Hydraulic Valve Assembly Type 4B Industrial Spec',
    date: '2026-08-15',
    unitOfMeasure: 'PCS',
    quantity: 20,
    unitCost: 340.00,
    unitPrice: 420.00,
    valueBeforeVat: 8400.00,
    vatRate: 0.18,
    vatAmount: 1512.00,
    valueAfterVat: 9912.00,
  },

  // PO-2026-9042 - Global Mining & Energy Corp (3 lines)
  {
    id: 'pol-sample-3',
    customerName: 'Global Mining & Energy Corp',
    destination: 'Mwanza Goldfield Logistics Hub',
    poNumber: 'PO-2026-9042',
    contract: 'CNT-MINE-442',
    itemDescription: 'Heavy Duty Conveyor Belt 1200mm (50m roll EP400/3)',
    date: '2026-08-20',
    unitOfMeasure: 'ROLLS',
    quantity: 15,
    unitCost: 1200.00,
    unitPrice: 1450.00,
    valueBeforeVat: 21750.00,
    vatRate: 0.18,
    vatAmount: 3915.00,
    valueAfterVat: 25665.00,
  },
  {
    id: 'pol-sample-4',
    customerName: 'Global Mining & Energy Corp',
    destination: 'Mwanza Goldfield Logistics Hub',
    poNumber: 'PO-2026-9042',
    contract: 'CNT-MINE-442',
    itemDescription: 'Industrial Lubricant Synthetic ISO VG 320 (200L Drum)',
    date: '2026-08-20',
    unitOfMeasure: 'DRUMS',
    quantity: 40,
    unitCost: 180.00,
    unitPrice: 230.00,
    valueBeforeVat: 9200.00,
    vatRate: 0.18,
    vatAmount: 1656.00,
    valueAfterVat: 10856.00,
  },
  {
    id: 'pol-sample-5',
    customerName: 'Global Mining & Energy Corp',
    destination: 'Mwanza Goldfield Logistics Hub',
    poNumber: 'PO-2026-9042',
    contract: 'CNT-MINE-442',
    itemDescription: 'Primary Crusher Manganese Jaw Liner Set',
    date: '2026-08-20',
    unitOfMeasure: 'SETS',
    quantity: 4,
    unitCost: 4500.00,
    unitPrice: 5600.00,
    valueBeforeVat: 22400.00,
    vatRate: 0.18,
    vatAmount: 4032.00,
    valueAfterVat: 26432.00,
  },

  // PO-2026-7730 - Kilimanjaro Agro Industries (2 lines)
  {
    id: 'pol-sample-6',
    customerName: 'Kilimanjaro Agro Industries',
    destination: 'Arusha Depot Warehouse 2',
    poNumber: 'PO-2026-7730',
    contract: 'CNT-AGRO-108',
    itemDescription: 'Drip Irrigation Poly Tubing 16mm UV Resistant (500m)',
    date: '2026-08-25',
    unitOfMeasure: 'COILS',
    quantity: 100,
    unitCost: 45.00,
    unitPrice: 60.00,
    valueBeforeVat: 6000.00,
    vatRate: 0.18,
    vatAmount: 1080.00,
    valueAfterVat: 7080.00,
  },
  {
    id: 'pol-sample-7',
    customerName: 'Kilimanjaro Agro Industries',
    destination: 'Arusha Depot Warehouse 2',
    poNumber: 'PO-2026-7730',
    contract: 'CNT-AGRO-108',
    itemDescription: 'Solar Powered Submersible Water Pump 3HP',
    date: '2026-08-25',
    unitOfMeasure: 'UNITS',
    quantity: 8,
    unitCost: 1100.00,
    unitPrice: 1350.00,
    valueBeforeVat: 10800.00,
    vatRate: 0.18,
    vatAmount: 1944.00,
    valueAfterVat: 12744.00,
  },

  // PO-2026-6519 - Serengeti Logistics & Haulage (2 lines)
  {
    id: 'pol-sample-8',
    customerName: 'Serengeti Logistics & Haulage',
    destination: 'Dodoma Central Freight Terminal',
    poNumber: 'PO-2026-6519',
    contract: 'CNT-LOG-780',
    itemDescription: 'Commercial Truck Tires 315/80R22.5 Premium Grip',
    date: '2026-08-28',
    unitOfMeasure: 'PCS',
    quantity: 32,
    unitCost: 290.00,
    unitPrice: 360.00,
    valueBeforeVat: 11520.00,
    vatRate: 0.18,
    vatAmount: 2073.60,
    valueAfterVat: 13593.60,
  },
  {
    id: 'pol-sample-9',
    customerName: 'Serengeti Logistics & Haulage',
    destination: 'Dodoma Central Freight Terminal',
    poNumber: 'PO-2026-6519',
    contract: 'CNT-LOG-780',
    itemDescription: 'Heavy Duty Truck Battery 12V 200Ah Maintenance Free',
    date: '2026-08-28',
    unitOfMeasure: 'PCS',
    quantity: 16,
    unitCost: 160.00,
    unitPrice: 210.00,
    valueBeforeVat: 3360.00,
    vatRate: 0.18,
    vatAmount: 604.80,
    valueAfterVat: 3964.80,
  },
];

export const INITIAL_INVOICES: any[] = [
  // Sample partial invoice against PO-2026-8801
  {
    id: 'inv-sample-1',
    invoiceNumber: 'INV-2026-001',
    invoiceDate: '2026-08-22',
    poNumber: 'PO-2026-8801',
    customerName: 'Acme Engineering Ltd',
    destination: 'Dar es Salaam Port - Site A',
    contract: 'CNT-EAST-091',
    poDate: '2026-08-15',
    lines: [
      {
        poLineId: 'pol-sample-1',
        itemDescription: 'High-Grade Steel Reinforcement Bars 16mm (Grade 500)',
        unitOfMeasure: 'TONS',
        poQuantity: 50,
        alreadyInvoicedQuantity: 0,
        availableQuantity: 50,
        invoicedQuantity: 30, // Partial 30 out of 50
        unitCost: 850.00,
        unitPrice: 980.00,
        valueBeforeVat: 29400.00,
        vatRate: 0.18,
        vatAmount: 5292.00,
        valueAfterVat: 34692.00,
        isSelected: true,
      },
      {
        poLineId: 'pol-sample-2',
        itemDescription: 'Hydraulic Valve Assembly Type 4B Industrial Spec',
        unitOfMeasure: 'PCS',
        poQuantity: 20,
        alreadyInvoicedQuantity: 0,
        availableQuantity: 20,
        invoicedQuantity: 20, // Full 20 out of 20
        unitCost: 340.00,
        unitPrice: 420.00,
        valueBeforeVat: 8400.00,
        vatRate: 0.18,
        vatAmount: 1512.00,
        valueAfterVat: 9912.00,
        isSelected: true,
      }
    ],
    subtotalBeforeVat: 37800.00,
    totalVat: 6804.00,
    totalAfterVat: 44604.00,
    paidAmount: 44604.00,
    paymentStatus: 'PAID',
    notes: 'Partial batch 1 shipment delivery against PO-2026-8801.',
    createdAt: '2026-08-22T10:30:00.000Z',
  }
];

export const INITIAL_DELIVERY_NOTES: any[] = [
  {
    id: 'dn-sample-1',
    deliveryNoteNumber: 'DN-2026-001',
    deliveryDate: '2026-08-21',
    poNumber: 'PO-2026-8801',
    customerName: 'Acme Engineering Ltd',
    destination: 'Dar es Salaam Port - Site A',
    contract: 'CNT-EAST-091',
    carrier: 'Express Freight Logistics (Truck T-492-DRL)',
    receivedBy: 'J. Mhando (Site Engineer)',
    lines: [
      {
        poLineId: 'pol-sample-1',
        itemDescription: 'High-Grade Steel Reinforcement Bars 16mm (Grade 500)',
        unitOfMeasure: 'TONS',
        poQuantity: 50,
        deliveredQuantity: 30,
        unitPrice: 980.00,
        valueAfterVat: 34692.00,
      },
      {
        poLineId: 'pol-sample-2',
        itemDescription: 'Hydraulic Valve Assembly Type 4B Industrial Spec',
        unitOfMeasure: 'PCS',
        poQuantity: 20,
        deliveredQuantity: 20,
        unitPrice: 420.00,
        valueAfterVat: 9912.00,
      }
    ],
    totalDeliveredQuantity: 50,
    totalDeliveredValue: 44604.00,
    notes: 'Received in good order at Site A warehouse dock.',
    createdAt: '2026-08-21T14:20:00.000Z',
  },
  {
    id: 'dn-sample-2',
    deliveryNoteNumber: 'DN-2026-002',
    deliveryDate: '2026-08-26',
    poNumber: 'PO-2026-9042',
    customerName: 'Global Mining & Energy Corp',
    destination: 'Mwanza Goldfield Logistics Hub',
    contract: 'CNT-MINE-442',
    carrier: 'Mwanza Heavy Haulage Ltd',
    receivedBy: 'P. Kazimoto (Inventory Controller)',
    lines: [
      {
        poLineId: 'pol-sample-3',
        itemDescription: 'Heavy Duty Conveyor Belt 1200mm (50m roll EP400/3)',
        unitOfMeasure: 'ROLLS',
        poQuantity: 15,
        deliveredQuantity: 10,
        unitPrice: 1450.00,
        valueAfterVat: 17110.00,
      },
      {
        poLineId: 'pol-sample-4',
        itemDescription: 'Industrial Lubricant Synthetic ISO VG 320 (200L Drum)',
        unitOfMeasure: 'DRUMS',
        poQuantity: 40,
        deliveredQuantity: 25,
        unitPrice: 230.00,
        valueAfterVat: 6785.00,
      }
    ],
    totalDeliveredQuantity: 35,
    totalDeliveredValue: 23895.00,
    notes: 'Primary dispatch of conveyor belts and lube drums.',
    createdAt: '2026-08-26T09:45:00.000Z',
  }
];

export const INITIAL_PAYMENTS: any[] = [
  {
    id: 'pay-sample-1',
    paymentNumber: 'PAY-2026-001',
    paymentDate: '2026-08-25',
    invoiceId: 'inv-sample-1',
    invoiceNumber: 'INV-2026-001',
    poNumber: 'PO-2026-8801',
    customerName: 'Acme Engineering Ltd',
    amountPaid: 44604.00,
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'TXN-STANBIC-9982104',
    notes: 'Full payment cleared for invoice INV-2026-001.',
    createdAt: '2026-08-25T11:00:00.000Z',
  }
];

export const INITIAL_DOCUMENT_ISSUES: DocumentIssueRecord[] = [
  {
    id: 'issue-inv-sample-1',
    entityType: 'INVOICE',
    entityId: 'inv-sample-1',
    referenceNumber: 'INV-2026-001',
    poNumber: 'PO-2026-8801',
    customerName: 'Acme Engineering Ltd',
    destination: 'Dar es Salaam Port - Site A',
    contract: 'CNT-EAST-091',
    totalValue: 44604.00,
    issueTitle: 'Quantity mismatch on Steel Reinforcement Bars (Line #1)',
    issueType: 'Quantity Discrepancy',
    severity: 'HIGH',
    status: 'PENDING',
    flaggedBy: 'Billing Clerk (Audit)',
    flaggedAt: '2026-08-23T14:15:00.000Z',
    headerComment: 'Client procurement notified that Line 1 invoiced 30 tons, but gate delivery receipt shows only 25 tons unloaded.',
    lineIssues: [
      {
        lineId: 'pol-sample-1',
        itemDescription: 'High-Grade Steel Reinforcement Bars 16mm (Grade 500)',
        unitOfMeasure: 'TONS',
        poQuantity: 50,
        billedOrDeliveredQuantity: 30,
        unitPrice: 980.00,
        valueAfterVat: 34692.00,
        issueComment: 'Warehouse gate pass shows only 25 tons received on initial flatbed trailer. 5 tons remained in transit.',
        workComment: 'Site supervisor verified gate delivery log. Recommends loading invoice and adjusting billed quantity from 30 to 25 tons.',
        reviewerComment: '',
        status: 'PENDING',
      },
      {
        lineId: 'pol-sample-2',
        itemDescription: 'Hydraulic Valve Assembly Type 4B Industrial Spec',
        unitOfMeasure: 'PCS',
        poQuantity: 20,
        billedOrDeliveredQuantity: 20,
        unitPrice: 420.00,
        valueAfterVat: 9912.00,
        issueComment: '',
        workComment: 'Quantity and pricing verified correct (20 PCS delivered and verified).',
        reviewerComment: '',
        status: 'RESOLVED',
      }
    ],
    comments: [
      {
        id: 'comm-1',
        authorName: 'Billing Clerk (Audit)',
        authorRole: 'Billing Clerk',
        comment: 'Flagged after receipt of client discrepancy notice #ACME-DISC-091 regarding Line 1 tonnage.',
        createdAt: '2026-08-23T14:15:00.000Z',
        type: 'WORK_NOTE',
      },
      {
        id: 'comm-2',
        authorName: 'Finance Officer',
        authorRole: 'Finance Officer',
        comment: 'Spoke with logistics carrier. Second truck with 5 tons will arrive next week under separate delivery. Please reload this invoice, amend Line 1 to 25 tons, and re-save so client can pay the approved balance.',
        createdAt: '2026-08-24T09:30:00.000Z',
        type: 'WORK_NOTE',
      }
    ]
  },
  {
    id: 'issue-dn-sample-2',
    entityType: 'DELIVERY',
    entityId: 'dn-sample-2',
    referenceNumber: 'DN-2026-002',
    poNumber: 'PO-2026-9042',
    customerName: 'Global Mining & Energy Corp',
    destination: 'Mwanza Goldfield Logistics Hub',
    contract: 'CNT-MINE-442',
    totalValue: 23895.00,
    issueTitle: 'Missing manufacturer ISO quality certificate for Conveyor Belt',
    issueType: 'Customer Query',
    severity: 'MEDIUM',
    status: 'UNDER_REVIEW',
    flaggedBy: 'Logistics Manager',
    flaggedAt: '2026-08-27T11:00:00.000Z',
    headerComment: 'Site engineer requested manufacturer ISO testing certificate for conveyor belt before signing acceptance.',
    lineIssues: [
      {
        lineId: 'pol-sample-3',
        itemDescription: 'Heavy Duty Conveyor Belt 1200mm (50m roll EP400/3)',
        unitOfMeasure: 'ROLLS',
        poQuantity: 15,
        billedOrDeliveredQuantity: 10,
        unitPrice: 1450.00,
        valueAfterVat: 17110.00,
        issueComment: 'Quality certificate attachment pending from shipping supplier.',
        workComment: 'Supplier emailed test certificate PDF. Sent to client site controller P. Kazimoto for review.',
        reviewerComment: 'Awaiting site controller written confirmation to mark resolved.',
        status: 'PENDING',
      }
    ],
    comments: [
      {
        id: 'comm-dn-1',
        authorName: 'Logistics Manager',
        authorRole: 'Logistics Manager',
        comment: 'Test certificate received from factory and transmitted to customer site team.',
        createdAt: '2026-08-27T11:30:00.000Z',
        type: 'WORK_NOTE',
      },
      {
        id: 'comm-dn-2',
        authorName: 'Auditor',
        authorRole: 'Auditor',
        comment: 'Put under review pending client written receipt confirmation.',
        createdAt: '2026-08-27T14:00:00.000Z',
        type: 'REVIEWER_NOTE',
      }
    ]
  },
  {
    id: 'issue-pay-sample-1',
    entityType: 'PAYMENT',
    entityId: 'pay-sample-1',
    referenceNumber: 'PAY-2026-001',
    poNumber: 'PO-2026-8801',
    customerName: 'Acme Engineering Ltd',
    totalValue: 44604.00,
    issueTitle: 'Bank SWIFT transaction reference verification',
    issueType: 'Payment Mismatch',
    severity: 'LOW',
    status: 'RESOLVED',
    flaggedBy: 'Finance Officer',
    flaggedAt: '2026-08-25T15:00:00.000Z',
    headerComment: 'Verify bank statement credit advice vs reference number TXN-STANBIC-9982104.',
    lineIssues: [],
    comments: [
      {
        id: 'comm-pay-1',
        authorName: 'Finance Officer',
        authorRole: 'Finance Officer',
        comment: 'Stanbic Bank statement verified. Funds cleared in USD primary account.',
        createdAt: '2026-08-26T08:00:00.000Z',
        type: 'WORK_NOTE',
      }
    ],
    resolvedBy: 'Admin',
    resolvedAt: '2026-08-26T08:15:00.000Z',
    resolutionNotes: 'Payment verified against bank statement. Cleared and reconciled.',
  }
];


